@REM This bat file has been generated by the IAR Embeddded Workbench
@REM C-SPY interactive debugger,as an aid to preparing a command
@REM line for running the cspybat command line utility with the
@REM appropriate settings.
@REM
@REM After making some adjustments to this file, you can launch cspybat
@REM by typing the name of this file followed by the name of the debug
@REM file (usually an ubrof file). Note that this file is generated
@REM every time a new debug session is initialized, so you may want to
@REM move or rename the file before making changes.
@REM
@REM Note: some command line arguments cannot be properly generated
@REM by this process. Specifically, the plugin which is responsible
@REM for the Terminal I/O window (and other C runtime functionality)
@REM comes in a special version for cspybat, and the name of that
@REM plugin dll is not known when generating this file. It resides in
@REM the $TOOLKIT_DIR$\bin folder and is usually called XXXbat.dll or
@REM XXXlibsupportbat.dll, where XXX is the name of the corresponding
@REM tool chain. Replace the '<libsupport_plugin>' parameter
@REM below with the appropriate file name. Other plugins loaded by
@REM C-SPY are usually not needed by, or will not work in, cspybat
@REM but they are listed at the end of this file for reference.


"E:\Program Files (x86)\common\bin\cspybat" "E:\Program Files (x86)\arm\bin\armproc.dll" "E:\Program Files (x86)\arm\bin\armstlink.dll"  %1 --plugin "E:\Program Files (x86)\arm\bin\<libsupport_plugin>" --flash_loader "E:\Program Files (x86)\arm\config\flashloader\ST\FlashSTM32F10xxE.board" --backend -B "--endian=little" "--cpu=Cortex-M3" "--fpu=None" "-p" "E:\Program Files (x86)\arm\CONFIG\debugger\ST\iostm32f10xxe.ddf" "--drv_verify_download" "--semihosting" "--device=STM32F10xxE" "-d" "stlink" 


@REM Loaded plugins:
@REM    E:\Program Files (x86)\arm\bin\armlibsupport.dll
@REM    E:\Program Files (x86)\common\plugins\CodeCoverage\CodeCoverage.dll
@REM    E:\Program Files (x86)\common\plugins\Profiling\Profiling.dll
@REM    E:\Program Files (x86)\common\plugins\stack\stack.dll
@REM    E:\Program Files (x86)\common\plugins\SymList\SymList.dll
